# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SwiftAdv' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SwiftAdv
  pod 'GoogleMaps'
  pod 'RealmSwift'
  pod 'SAMKeychain'
  pod 'RxSwift'
  pod 'RxCocoa'

  target 'SwiftAdvTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SwiftAdvUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
